# Generated by Django 5.2.1 on 2025-09-29 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectioncase',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cases', to='django_interface.patient'),
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('is_patient_the_payer', models.BooleanField(db_index=True, default=True, help_text='Flag que indica se os dados deste pagador são um espelho do paciente.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payers', to='django_interface.address')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='django_interface.patient')),
            ],
            options={
                'db_table': 'payers',
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='django_interface.payer'),
        ),
        migrations.CreateModel(
            name='PayerPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_type', models.CharField(blank=True, choices=[('home', 'Residencial'), ('mobile', 'Celular'), ('commercial', 'Comercial')], max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='django_interface.payer')),
            ],
            options={
                'db_table': 'payer_phones',
            },
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['patient', 'is_patient_the_payer'], name='payers_patient_be6695_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payer',
            unique_together={('patient', 'name', 'document')},
        ),
        migrations.AddIndex(
            model_name='payerphone',
            index=models.Index(fields=['payer'], name='payer_phone_payer_i_5e2cf2_idx'),
        ),
    ]